import { t } from "@/lib/i18n";

const fixed = new Map<string, Parameters<typeof t>[0]>([
  ["Computer preference: cloud computer.", "botSettings.overview.line.computerCloud"],
  ["Computer preference: Local VM.", "botSettings.overview.line.computerVm"],
  ["Computer preference: this computer.", "botSettings.overview.line.computerLocal"],
  ["Computer preference: browser only.", "botSettings.overview.line.computerBrowser"],
  ["Computer preference: Auto; availability is checked when a task starts.", "botSettings.overview.line.computerAuto"],
  ["Works in its private workspace.", "botSettings.overview.line.privateWorkspace"],
  ["Connected apps could not be checked.", "botSettings.overview.line.appsUnchecked"],
  ["Has the built-in browser.", "botSettings.overview.line.browser"],
  ["Coordinates its section as Chief of Staff.", "botSettings.overview.line.chief"],
  ["Command approvals use Ask mode; saved permissions and provider rules still apply.", "botSettings.overview.line.approvalAsk"],
  ["Command approvals follow the provider's custom configuration.", "botSettings.overview.line.approvalCustom"],
  ["Cannot initiate contact with other bots.", "botSettings.overview.line.noPeerContact"],
  ["Asks before contacting other bots.", "botSettings.overview.line.askPeerContact"],
  ["Has no connected apps.", "botSettings.overview.line.noApps"],
  ["Can't use a computer.", "botSettings.overview.line.noComputer"],
  ["Won't act on a schedule.", "botSettings.overview.line.noSchedule"],
  ["Profile proposal cards require your approval.", "botSettings.overview.line.profileApproval"],
]);

/** Localize only sentences generated by server/bot-overview.ts. Bot names,
 * paths, service names, profile text, and history summaries remain data. */
export function localizeOverviewLine(line: string): string {
  const key = fixed.get(line);
  if (key) return t(key);

  let match = /^Works in (.+)\.$/.exec(line);
  if (match) return t("botSettings.overview.line.workspace", { path: match[1]! });
  match = /^Can use (\d+) connected apps?: (.+)\.$/.exec(line);
  if (match) return t("botSettings.overview.line.apps", { count: match[1]!, services: match[2]! });
  match = /^Can talk to (\d+) other bots? in its section\.$/.exec(line);
  if (match) return t("botSettings.overview.line.peers", { count: match[1]! });
  match = /^Paused: (.+)\.$/.exec(line);
  if (match) return t("botSettings.overview.line.paused", { name: match[1]! });
  match = /^Knows how to (.+)\.$/.exec(line);
  if (match) return t("botSettings.overview.line.knows", { skill: match[1]! });
  match = /^Listens for “(.+)” webhooks\.$/.exec(line);
  if (match) return t("botSettings.overview.line.webhook", { name: match[1]! });
  return line;
}
